### ISSUE TITLE
Old server

### ISSUE THREAD

**Issue by hauk92** [dokuwiki/download.dokuwiki.org#8]
The downloaded archives for DokuWikiStick still contain the old apache server.

**Comment by splitbrain** [comment]
Hmm. I deleted the caches, can you try again?

**Comment by hauk92** [comment]
Still not working. https://download.dokuwiki.org/get?id=de17c857c5ae3a457ca98ff25cf6668d should be newly generated and still contains old files.

**Comment by hauk92** [comment]
Old files is maybe misleading. Most of them got a new timestamp.
![image](https://github.com/dokuwiki/download.dokuwiki.org/assets/47572039/f2b71612-0b6b-4f79-8dbd-5f7d6572d636)
run.cmd is truly old.
![image](https://github.com/dokuwiki/download.dokuwiki.org/assets/47572039/36d0a2dc-536e-4154-846f-1620004f6e1d)

**Comment by hauk92** [comment]
Looks good now!
